[platformio]
default_envs = sticks3

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
monitor_speed = 115200
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified.git#8530f5377d782e4a25a6c482de2e71c3f75ca8eb
    M5PM1=https://github.com/m5stack/M5PM1.git#be9a5456c007c333e7ac963f33bfde1ffa5d82ee
    M5GFX=https://github.com/m5stack/M5GFX.git#d91077b9a607b59404e4e4a49f775c792bfae382

[env:sticks3]
